version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: 'graphql-recipe'
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}